// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CustomMsg.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_CustomMsg_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_CustomMsg_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "ignition/msgs/time.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_CustomMsg_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_CustomMsg_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_CustomMsg_2eproto;
namespace LivoxCustomMsg {
class CustomMsg;
class CustomMsgDefaultTypeInternal;
extern CustomMsgDefaultTypeInternal _CustomMsg_default_instance_;
class CustomPoint;
class CustomPointDefaultTypeInternal;
extern CustomPointDefaultTypeInternal _CustomPoint_default_instance_;
}  // namespace LivoxCustomMsg
PROTOBUF_NAMESPACE_OPEN
template<> ::LivoxCustomMsg::CustomMsg* Arena::CreateMaybeMessage<::LivoxCustomMsg::CustomMsg>(Arena*);
template<> ::LivoxCustomMsg::CustomPoint* Arena::CreateMaybeMessage<::LivoxCustomMsg::CustomPoint>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace LivoxCustomMsg {

// ===================================================================

class CustomPoint PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:LivoxCustomMsg.CustomPoint) */ {
 public:
  inline CustomPoint() : CustomPoint(nullptr) {};
  virtual ~CustomPoint();

  CustomPoint(const CustomPoint& from);
  CustomPoint(CustomPoint&& from) noexcept
    : CustomPoint() {
    *this = ::std::move(from);
  }

  inline CustomPoint& operator=(const CustomPoint& from) {
    CopyFrom(from);
    return *this;
  }
  inline CustomPoint& operator=(CustomPoint&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const CustomPoint& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CustomPoint* internal_default_instance() {
    return reinterpret_cast<const CustomPoint*>(
               &_CustomPoint_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(CustomPoint& a, CustomPoint& b) {
    a.Swap(&b);
  }
  inline void Swap(CustomPoint* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CustomPoint* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline CustomPoint* New() const final {
    return CreateMaybeMessage<CustomPoint>(nullptr);
  }

  CustomPoint* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CustomPoint>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const CustomPoint& from);
  void MergeFrom(const CustomPoint& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CustomPoint* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "LivoxCustomMsg.CustomPoint";
  }
  protected:
  explicit CustomPoint(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_CustomMsg_2eproto);
    return ::descriptor_table_CustomMsg_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kOffsetTimeFieldNumber = 1,
    kXFieldNumber = 2,
    kYFieldNumber = 3,
    kZFieldNumber = 4,
    kReflectivityFieldNumber = 5,
    kTagFieldNumber = 6,
    kLineFieldNumber = 7,
  };
  // uint32 offset_time = 1;
  void clear_offset_time();
  ::PROTOBUF_NAMESPACE_ID::uint32 offset_time() const;
  void set_offset_time(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_offset_time() const;
  void _internal_set_offset_time(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // float x = 2;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // float y = 3;
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // float z = 4;
  void clear_z();
  float z() const;
  void set_z(float value);
  private:
  float _internal_z() const;
  void _internal_set_z(float value);
  public:

  // uint32 reflectivity = 5;
  void clear_reflectivity();
  ::PROTOBUF_NAMESPACE_ID::uint32 reflectivity() const;
  void set_reflectivity(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_reflectivity() const;
  void _internal_set_reflectivity(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 tag = 6;
  void clear_tag();
  ::PROTOBUF_NAMESPACE_ID::uint32 tag() const;
  void set_tag(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_tag() const;
  void _internal_set_tag(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 line = 7;
  void clear_line();
  ::PROTOBUF_NAMESPACE_ID::uint32 line() const;
  void set_line(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_line() const;
  void _internal_set_line(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:LivoxCustomMsg.CustomPoint)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::uint32 offset_time_;
  float x_;
  float y_;
  float z_;
  ::PROTOBUF_NAMESPACE_ID::uint32 reflectivity_;
  ::PROTOBUF_NAMESPACE_ID::uint32 tag_;
  ::PROTOBUF_NAMESPACE_ID::uint32 line_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_CustomMsg_2eproto;
};
// -------------------------------------------------------------------

class CustomMsg PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:LivoxCustomMsg.CustomMsg) */ {
 public:
  inline CustomMsg() : CustomMsg(nullptr) {};
  virtual ~CustomMsg();

  CustomMsg(const CustomMsg& from);
  CustomMsg(CustomMsg&& from) noexcept
    : CustomMsg() {
    *this = ::std::move(from);
  }

  inline CustomMsg& operator=(const CustomMsg& from) {
    CopyFrom(from);
    return *this;
  }
  inline CustomMsg& operator=(CustomMsg&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const CustomMsg& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CustomMsg* internal_default_instance() {
    return reinterpret_cast<const CustomMsg*>(
               &_CustomMsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(CustomMsg& a, CustomMsg& b) {
    a.Swap(&b);
  }
  inline void Swap(CustomMsg* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CustomMsg* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline CustomMsg* New() const final {
    return CreateMaybeMessage<CustomMsg>(nullptr);
  }

  CustomMsg* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CustomMsg>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const CustomMsg& from);
  void MergeFrom(const CustomMsg& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CustomMsg* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "LivoxCustomMsg.CustomMsg";
  }
  protected:
  explicit CustomMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_CustomMsg_2eproto);
    return ::descriptor_table_CustomMsg_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPointsFieldNumber = 9,
    kFrameIdFieldNumber = 2,
    kStampFieldNumber = 1,
    kTimeBaseFieldNumber = 3,
    kPointNumFieldNumber = 4,
    kLidarIdFieldNumber = 5,
    kRsvd0FieldNumber = 6,
    kRsvd1FieldNumber = 7,
    kRsvd2FieldNumber = 8,
  };
  // repeated .LivoxCustomMsg.CustomPoint points = 9;
  int points_size() const;
  private:
  int _internal_points_size() const;
  public:
  void clear_points();
  ::LivoxCustomMsg::CustomPoint* mutable_points(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::LivoxCustomMsg::CustomPoint >*
      mutable_points();
  private:
  const ::LivoxCustomMsg::CustomPoint& _internal_points(int index) const;
  ::LivoxCustomMsg::CustomPoint* _internal_add_points();
  public:
  const ::LivoxCustomMsg::CustomPoint& points(int index) const;
  ::LivoxCustomMsg::CustomPoint* add_points();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::LivoxCustomMsg::CustomPoint >&
      points() const;

  // string frame_id = 2;
  bool has_frame_id() const;
  private:
  bool _internal_has_frame_id() const;
  public:
  void clear_frame_id();
  const std::string& frame_id() const;
  void set_frame_id(const std::string& value);
  void set_frame_id(std::string&& value);
  void set_frame_id(const char* value);
  void set_frame_id(const char* value, size_t size);
  std::string* mutable_frame_id();
  std::string* release_frame_id();
  void set_allocated_frame_id(std::string* frame_id);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_frame_id();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_frame_id(
      std::string* frame_id);
  private:
  const std::string& _internal_frame_id() const;
  void _internal_set_frame_id(const std::string& value);
  std::string* _internal_mutable_frame_id();
  public:

  // .ignition.msgs.Time stamp = 1;
  bool has_stamp() const;
  private:
  bool _internal_has_stamp() const;
  public:
  void clear_stamp();
  const ::ignition::msgs::Time& stamp() const;
  ::ignition::msgs::Time* release_stamp();
  ::ignition::msgs::Time* mutable_stamp();
  void set_allocated_stamp(::ignition::msgs::Time* stamp);
  private:
  const ::ignition::msgs::Time& _internal_stamp() const;
  ::ignition::msgs::Time* _internal_mutable_stamp();
  public:
  void unsafe_arena_set_allocated_stamp(
      ::ignition::msgs::Time* stamp);
  ::ignition::msgs::Time* unsafe_arena_release_stamp();

  // uint64 time_base = 3;
  void clear_time_base();
  ::PROTOBUF_NAMESPACE_ID::uint64 time_base() const;
  void set_time_base(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_time_base() const;
  void _internal_set_time_base(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint32 point_num = 4;
  void clear_point_num();
  ::PROTOBUF_NAMESPACE_ID::uint32 point_num() const;
  void set_point_num(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_point_num() const;
  void _internal_set_point_num(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 lidar_id = 5;
  void clear_lidar_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 lidar_id() const;
  void set_lidar_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_lidar_id() const;
  void _internal_set_lidar_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 rsvd_0 = 6;
  void clear_rsvd_0();
  ::PROTOBUF_NAMESPACE_ID::uint32 rsvd_0() const;
  void set_rsvd_0(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_rsvd_0() const;
  void _internal_set_rsvd_0(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 rsvd_1 = 7;
  void clear_rsvd_1();
  ::PROTOBUF_NAMESPACE_ID::uint32 rsvd_1() const;
  void set_rsvd_1(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_rsvd_1() const;
  void _internal_set_rsvd_1(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 rsvd_2 = 8;
  void clear_rsvd_2();
  ::PROTOBUF_NAMESPACE_ID::uint32 rsvd_2() const;
  void set_rsvd_2(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_rsvd_2() const;
  void _internal_set_rsvd_2(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:LivoxCustomMsg.CustomMsg)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::LivoxCustomMsg::CustomPoint > points_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr frame_id_;
  ::ignition::msgs::Time* stamp_;
  ::PROTOBUF_NAMESPACE_ID::uint64 time_base_;
  ::PROTOBUF_NAMESPACE_ID::uint32 point_num_;
  ::PROTOBUF_NAMESPACE_ID::uint32 lidar_id_;
  ::PROTOBUF_NAMESPACE_ID::uint32 rsvd_0_;
  ::PROTOBUF_NAMESPACE_ID::uint32 rsvd_1_;
  ::PROTOBUF_NAMESPACE_ID::uint32 rsvd_2_;
  friend struct ::TableStruct_CustomMsg_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CustomPoint

// uint32 offset_time = 1;
inline void CustomPoint::clear_offset_time() {
  offset_time_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CustomPoint::_internal_offset_time() const {
  return offset_time_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CustomPoint::offset_time() const {
  // @@protoc_insertion_point(field_get:LivoxCustomMsg.CustomPoint.offset_time)
  return _internal_offset_time();
}
inline void CustomPoint::_internal_set_offset_time(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  offset_time_ = value;
}
inline void CustomPoint::set_offset_time(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_offset_time(value);
  // @@protoc_insertion_point(field_set:LivoxCustomMsg.CustomPoint.offset_time)
}

// float x = 2;
inline void CustomPoint::clear_x() {
  x_ = 0;
}
inline float CustomPoint::_internal_x() const {
  return x_;
}
inline float CustomPoint::x() const {
  // @@protoc_insertion_point(field_get:LivoxCustomMsg.CustomPoint.x)
  return _internal_x();
}
inline void CustomPoint::_internal_set_x(float value) {
  
  x_ = value;
}
inline void CustomPoint::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:LivoxCustomMsg.CustomPoint.x)
}

// float y = 3;
inline void CustomPoint::clear_y() {
  y_ = 0;
}
inline float CustomPoint::_internal_y() const {
  return y_;
}
inline float CustomPoint::y() const {
  // @@protoc_insertion_point(field_get:LivoxCustomMsg.CustomPoint.y)
  return _internal_y();
}
inline void CustomPoint::_internal_set_y(float value) {
  
  y_ = value;
}
inline void CustomPoint::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:LivoxCustomMsg.CustomPoint.y)
}

// float z = 4;
inline void CustomPoint::clear_z() {
  z_ = 0;
}
inline float CustomPoint::_internal_z() const {
  return z_;
}
inline float CustomPoint::z() const {
  // @@protoc_insertion_point(field_get:LivoxCustomMsg.CustomPoint.z)
  return _internal_z();
}
inline void CustomPoint::_internal_set_z(float value) {
  
  z_ = value;
}
inline void CustomPoint::set_z(float value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:LivoxCustomMsg.CustomPoint.z)
}

// uint32 reflectivity = 5;
inline void CustomPoint::clear_reflectivity() {
  reflectivity_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CustomPoint::_internal_reflectivity() const {
  return reflectivity_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CustomPoint::reflectivity() const {
  // @@protoc_insertion_point(field_get:LivoxCustomMsg.CustomPoint.reflectivity)
  return _internal_reflectivity();
}
inline void CustomPoint::_internal_set_reflectivity(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  reflectivity_ = value;
}
inline void CustomPoint::set_reflectivity(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_reflectivity(value);
  // @@protoc_insertion_point(field_set:LivoxCustomMsg.CustomPoint.reflectivity)
}

// uint32 tag = 6;
inline void CustomPoint::clear_tag() {
  tag_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CustomPoint::_internal_tag() const {
  return tag_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CustomPoint::tag() const {
  // @@protoc_insertion_point(field_get:LivoxCustomMsg.CustomPoint.tag)
  return _internal_tag();
}
inline void CustomPoint::_internal_set_tag(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  tag_ = value;
}
inline void CustomPoint::set_tag(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_tag(value);
  // @@protoc_insertion_point(field_set:LivoxCustomMsg.CustomPoint.tag)
}

// uint32 line = 7;
inline void CustomPoint::clear_line() {
  line_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CustomPoint::_internal_line() const {
  return line_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CustomPoint::line() const {
  // @@protoc_insertion_point(field_get:LivoxCustomMsg.CustomPoint.line)
  return _internal_line();
}
inline void CustomPoint::_internal_set_line(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  line_ = value;
}
inline void CustomPoint::set_line(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_line(value);
  // @@protoc_insertion_point(field_set:LivoxCustomMsg.CustomPoint.line)
}

// -------------------------------------------------------------------

// CustomMsg

// .ignition.msgs.Time stamp = 1;
inline bool CustomMsg::_internal_has_stamp() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || stamp_ != nullptr);
  return value;
}
inline bool CustomMsg::has_stamp() const {
  return _internal_has_stamp();
}
inline const ::ignition::msgs::Time& CustomMsg::_internal_stamp() const {
  const ::ignition::msgs::Time* p = stamp_;
  return p != nullptr ? *p : *reinterpret_cast<const ::ignition::msgs::Time*>(
      &::ignition::msgs::_Time_default_instance_);
}
inline const ::ignition::msgs::Time& CustomMsg::stamp() const {
  // @@protoc_insertion_point(field_get:LivoxCustomMsg.CustomMsg.stamp)
  return _internal_stamp();
}
inline void CustomMsg::unsafe_arena_set_allocated_stamp(
    ::ignition::msgs::Time* stamp) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(stamp_);
  }
  stamp_ = stamp;
  if (stamp) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:LivoxCustomMsg.CustomMsg.stamp)
}
inline ::ignition::msgs::Time* CustomMsg::release_stamp() {
  auto temp = unsafe_arena_release_stamp();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::ignition::msgs::Time* CustomMsg::unsafe_arena_release_stamp() {
  // @@protoc_insertion_point(field_release:LivoxCustomMsg.CustomMsg.stamp)
  _has_bits_[0] &= ~0x00000002u;
  ::ignition::msgs::Time* temp = stamp_;
  stamp_ = nullptr;
  return temp;
}
inline ::ignition::msgs::Time* CustomMsg::_internal_mutable_stamp() {
  _has_bits_[0] |= 0x00000002u;
  if (stamp_ == nullptr) {
    auto* p = CreateMaybeMessage<::ignition::msgs::Time>(GetArena());
    stamp_ = p;
  }
  return stamp_;
}
inline ::ignition::msgs::Time* CustomMsg::mutable_stamp() {
  // @@protoc_insertion_point(field_mutable:LivoxCustomMsg.CustomMsg.stamp)
  return _internal_mutable_stamp();
}
inline void CustomMsg::set_allocated_stamp(::ignition::msgs::Time* stamp) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(stamp_);
  }
  if (stamp) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(stamp)->GetArena();
    if (message_arena != submessage_arena) {
      stamp = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, stamp, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  stamp_ = stamp;
  // @@protoc_insertion_point(field_set_allocated:LivoxCustomMsg.CustomMsg.stamp)
}

// string frame_id = 2;
inline bool CustomMsg::_internal_has_frame_id() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool CustomMsg::has_frame_id() const {
  return _internal_has_frame_id();
}
inline void CustomMsg::clear_frame_id() {
  frame_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& CustomMsg::frame_id() const {
  // @@protoc_insertion_point(field_get:LivoxCustomMsg.CustomMsg.frame_id)
  return _internal_frame_id();
}
inline void CustomMsg::set_frame_id(const std::string& value) {
  _internal_set_frame_id(value);
  // @@protoc_insertion_point(field_set:LivoxCustomMsg.CustomMsg.frame_id)
}
inline std::string* CustomMsg::mutable_frame_id() {
  // @@protoc_insertion_point(field_mutable:LivoxCustomMsg.CustomMsg.frame_id)
  return _internal_mutable_frame_id();
}
inline const std::string& CustomMsg::_internal_frame_id() const {
  return frame_id_.Get();
}
inline void CustomMsg::_internal_set_frame_id(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  frame_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void CustomMsg::set_frame_id(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  frame_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:LivoxCustomMsg.CustomMsg.frame_id)
}
inline void CustomMsg::set_frame_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  frame_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:LivoxCustomMsg.CustomMsg.frame_id)
}
inline void CustomMsg::set_frame_id(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  frame_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:LivoxCustomMsg.CustomMsg.frame_id)
}
inline std::string* CustomMsg::_internal_mutable_frame_id() {
  _has_bits_[0] |= 0x00000001u;
  return frame_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* CustomMsg::release_frame_id() {
  // @@protoc_insertion_point(field_release:LivoxCustomMsg.CustomMsg.frame_id)
  if (!_internal_has_frame_id()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return frame_id_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void CustomMsg::set_allocated_frame_id(std::string* frame_id) {
  if (frame_id != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  frame_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), frame_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:LivoxCustomMsg.CustomMsg.frame_id)
}
inline std::string* CustomMsg::unsafe_arena_release_frame_id() {
  // @@protoc_insertion_point(field_unsafe_arena_release:LivoxCustomMsg.CustomMsg.frame_id)
  GOOGLE_DCHECK(GetArena() != nullptr);
  _has_bits_[0] &= ~0x00000001u;
  return frame_id_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void CustomMsg::unsafe_arena_set_allocated_frame_id(
    std::string* frame_id) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (frame_id != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  frame_id_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      frame_id, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:LivoxCustomMsg.CustomMsg.frame_id)
}

// uint64 time_base = 3;
inline void CustomMsg::clear_time_base() {
  time_base_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 CustomMsg::_internal_time_base() const {
  return time_base_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 CustomMsg::time_base() const {
  // @@protoc_insertion_point(field_get:LivoxCustomMsg.CustomMsg.time_base)
  return _internal_time_base();
}
inline void CustomMsg::_internal_set_time_base(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  time_base_ = value;
}
inline void CustomMsg::set_time_base(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_time_base(value);
  // @@protoc_insertion_point(field_set:LivoxCustomMsg.CustomMsg.time_base)
}

// uint32 point_num = 4;
inline void CustomMsg::clear_point_num() {
  point_num_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CustomMsg::_internal_point_num() const {
  return point_num_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CustomMsg::point_num() const {
  // @@protoc_insertion_point(field_get:LivoxCustomMsg.CustomMsg.point_num)
  return _internal_point_num();
}
inline void CustomMsg::_internal_set_point_num(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  point_num_ = value;
}
inline void CustomMsg::set_point_num(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_point_num(value);
  // @@protoc_insertion_point(field_set:LivoxCustomMsg.CustomMsg.point_num)
}

// uint32 lidar_id = 5;
inline void CustomMsg::clear_lidar_id() {
  lidar_id_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CustomMsg::_internal_lidar_id() const {
  return lidar_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CustomMsg::lidar_id() const {
  // @@protoc_insertion_point(field_get:LivoxCustomMsg.CustomMsg.lidar_id)
  return _internal_lidar_id();
}
inline void CustomMsg::_internal_set_lidar_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  lidar_id_ = value;
}
inline void CustomMsg::set_lidar_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_lidar_id(value);
  // @@protoc_insertion_point(field_set:LivoxCustomMsg.CustomMsg.lidar_id)
}

// uint32 rsvd_0 = 6;
inline void CustomMsg::clear_rsvd_0() {
  rsvd_0_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CustomMsg::_internal_rsvd_0() const {
  return rsvd_0_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CustomMsg::rsvd_0() const {
  // @@protoc_insertion_point(field_get:LivoxCustomMsg.CustomMsg.rsvd_0)
  return _internal_rsvd_0();
}
inline void CustomMsg::_internal_set_rsvd_0(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  rsvd_0_ = value;
}
inline void CustomMsg::set_rsvd_0(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_rsvd_0(value);
  // @@protoc_insertion_point(field_set:LivoxCustomMsg.CustomMsg.rsvd_0)
}

// uint32 rsvd_1 = 7;
inline void CustomMsg::clear_rsvd_1() {
  rsvd_1_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CustomMsg::_internal_rsvd_1() const {
  return rsvd_1_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CustomMsg::rsvd_1() const {
  // @@protoc_insertion_point(field_get:LivoxCustomMsg.CustomMsg.rsvd_1)
  return _internal_rsvd_1();
}
inline void CustomMsg::_internal_set_rsvd_1(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  rsvd_1_ = value;
}
inline void CustomMsg::set_rsvd_1(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_rsvd_1(value);
  // @@protoc_insertion_point(field_set:LivoxCustomMsg.CustomMsg.rsvd_1)
}

// uint32 rsvd_2 = 8;
inline void CustomMsg::clear_rsvd_2() {
  rsvd_2_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CustomMsg::_internal_rsvd_2() const {
  return rsvd_2_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CustomMsg::rsvd_2() const {
  // @@protoc_insertion_point(field_get:LivoxCustomMsg.CustomMsg.rsvd_2)
  return _internal_rsvd_2();
}
inline void CustomMsg::_internal_set_rsvd_2(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  rsvd_2_ = value;
}
inline void CustomMsg::set_rsvd_2(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_rsvd_2(value);
  // @@protoc_insertion_point(field_set:LivoxCustomMsg.CustomMsg.rsvd_2)
}

// repeated .LivoxCustomMsg.CustomPoint points = 9;
inline int CustomMsg::_internal_points_size() const {
  return points_.size();
}
inline int CustomMsg::points_size() const {
  return _internal_points_size();
}
inline void CustomMsg::clear_points() {
  points_.Clear();
}
inline ::LivoxCustomMsg::CustomPoint* CustomMsg::mutable_points(int index) {
  // @@protoc_insertion_point(field_mutable:LivoxCustomMsg.CustomMsg.points)
  return points_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::LivoxCustomMsg::CustomPoint >*
CustomMsg::mutable_points() {
  // @@protoc_insertion_point(field_mutable_list:LivoxCustomMsg.CustomMsg.points)
  return &points_;
}
inline const ::LivoxCustomMsg::CustomPoint& CustomMsg::_internal_points(int index) const {
  return points_.Get(index);
}
inline const ::LivoxCustomMsg::CustomPoint& CustomMsg::points(int index) const {
  // @@protoc_insertion_point(field_get:LivoxCustomMsg.CustomMsg.points)
  return _internal_points(index);
}
inline ::LivoxCustomMsg::CustomPoint* CustomMsg::_internal_add_points() {
  return points_.Add();
}
inline ::LivoxCustomMsg::CustomPoint* CustomMsg::add_points() {
  // @@protoc_insertion_point(field_add:LivoxCustomMsg.CustomMsg.points)
  return _internal_add_points();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::LivoxCustomMsg::CustomPoint >&
CustomMsg::points() const {
  // @@protoc_insertion_point(field_list:LivoxCustomMsg.CustomMsg.points)
  return points_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace LivoxCustomMsg

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_CustomMsg_2eproto
